@startuml

object GameObject <<Unity>>

interface ISpawnable {
	+LocalPositionOffset : Vector3 
	+AddMonoBehaviour<AbstractCustomMonoBehaviour>() : void
	+SetLocalPositionOffset(Vector3) : void
	+Spawn(Transform) : void
	+OnDestroy() : void 
}

interface ICreateable {
	+Create() : GameObject
}

class CustomGameObject <<AbstractCustomGameObject>> {
	+Name : string
	#CustomPrefabName : string 
	#GameObjectInstance : GameObject
}

class CustomPrefab <<AbstractCustomPrefab>> {
	#NewPrefabName : string
	#SourcePrefabName : string
	.. Constructor ..
	+CustomPrefab(string, string) : CustomPrefab
	--
	#OnCreate(GameObject) : GameObject 
}

class CustomMonoBehaviour <<AbstractCustomMonoBehaviour>> {
	#Say(GameObject, string, string) : void

}

CustomGameObject "1" *-- "1" GameObject : has a >
CustomGameObject "1" *-- "1" CustomPrefab : has a >
ICreateable <|-- CustomPrefab : implements
CustomPrefab o-- GameObject : creates a >
MonoBehaviour <|-- CustomMonoBehaviour : is a
ISpawnable <|-- CustomGameObject : implements
CustomGameObject "1" *-- "0..*" CustomMonoBehaviour : has a >

@enduml